[env:t-a7670e]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -mfix-esp32-psram-cache-issue
    -DLILYGO_T_A7670
lib_deps =
    https://github.com/lewisxhe/TinyGSM-fork.git
