[platformio]
default_envs = t-a7670e

[env]
platform = espressif32@6.12.0
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -mfix-esp32-psram-cache-issue
lib_deps =
    https://github.com/lewisxhe/TinyGSM-fork.git

[env:esp32_base]
extends = env
board = esp32dev

[env:esp32s3_base]
extends = env
board = esp32-s3-devkitc-1

[env:t-a7670e]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_T_A7670

[env:t-call-a7670-v1-0]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_T_CALL_A7670_V1_0

[env:t-call-a7670-v1-1]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_T_CALL_A7670_V1_1

[env:t-sim7670g-s3]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_SIM7670G_S3

[env:t-a7608x]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_T_A7608X

[env:t-a7608x-s3]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_A7608X_S3

[env:sim7000g]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_SIM7000G

[env:sim7070g]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_SIM7070G

[env:sim7600x]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_SIM7600X

[env:sim7000g-s3-stan]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_SIM7000G_S3_STAN

[env:sim7080g-s3-stan]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_SIM7080G_S3_STAN

[env:sim7670g-s3-stan]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_SIM7670G_S3_STAN

[env:a7670x-s3-stan]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_A7670X_S3_STAN

[env:sim7600x-s3-stan]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_SIM7600X_S3_STAN

[env:sim7080g-s3]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_SIM7080G_S3

[env:t-relay-s3-simshield]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_RELAY_S3_SIMSHIELD

[env:t-pcie-a767x]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_T_PCIE_A767X

[env:t-pcie-sim7000g]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_T_PCIE_SIM7000G

[env:t-pcie-sim7080g]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_T_PCIE_SIM7080G

[env:t-pcie-sim7600x]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_T_PCIE_SIM7600X

[env:t-pcie-sim7670g]
extends = env:esp32_base
build_flags = ${env.build_flags} -DLILYGO_T_PCIE_SIM7670G

[env:t-eth-elite-a7670x]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_ETH_ELITE_A7670X

[env:t-eth-elite-sim7000x]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_ETH_ELITE_SIM7000X

[env:t-eth-elite-sim7080g]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_ETH_ELITE_SIM7080G

[env:t-eth-elite-sim7600x]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_ETH_ELITE_SIM7600X

[env:t-eth-elite-sim7670g]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_ETH_ELITE_SIM7670G

[env:t-internet-com-a7670x]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_INTERNET_COM_A7670X

[env:t-internet-com-sim7000x]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_INTERNET_COM_SIM7000X

[env:t-internet-com-sim7080g]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_INTERNET_COM_SIM7080G

[env:t-internet-com-sim7600x]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_INTERNET_COM_SIM7600X

[env:t-internet-com-sim7670g]
extends = env:esp32s3_base
build_flags = ${env.build_flags} -DLILYGO_T_INTERNET_COM_SIM7670G
