#pragma once

#include "app_config.h"

#define MODEM_BAUDRATE 115200
#define MODEM_DTR_PIN 25
#define MODEM_TX_PIN 26
#define MODEM_RX_PIN 27
#define BOARD_PWRKEY_PIN 4
#define BOARD_POWERON_PIN 12
#define MODEM_RING_PIN 33
#define MODEM_RESET_PIN 5
#define BOARD_BAT_ADC_PIN 35
#define MODEM_RESET_LEVEL HIGH
#define SerialAT Serial1

#define MODEM_GPS_ENABLE_GPIO (-1)
#define MODEM_GPS_ENABLE_LEVEL (-1)

#ifndef TINY_GSM_MODEM_A7670
#define TINY_GSM_MODEM_A7670
#endif

#define PRODUCT_MODEL_NAME "LilyGo-A7670 ESP32 Version"
#define MODEM_REG_SMS_ONLY

#define MODEM_POWERON_PULSE_WIDTH_MS 100
#define MODEM_POWEROFF_PULSE_WIDTH_MS 3000
#define MODEM_START_WAIT_MS 3000
